## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [ ]:
import numpy as np
np.__version__

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

* np.arange(start, stop, step, dtype=None)

 start = the start of the interval (inc)<br>
 stop  = the end of the interval (exc), <br>
 step  = the spacing between values<br> 
 dtype = the data type of the array<br>

In [ ]:
my_array = np.arange(10)
print(my_array)

## Ejercicio 3
Crea un array 3x3, que sea todo a True
* np.full(shape, fill_value, dtype=None, order='C', *, like=None)<br>

The shape parameter = the shape of the new array, <br>
the fill_value parameter = the value to fill the array with,<br>
the dtype parameter = the data type of the array.<br>

* order: An optional parameter that specifies whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory. It defaults to 'C'.

* like: An optional parameter that specifies a reference object to allow the creation of arrays which are not NumPy arrays. If an array-like object is passed in as like and supports the __array_function__ protocol, the result will be defined by it. (This parameter was introduced in version 1.20.0.)

(The order and like parameters are optional, use 'C' or 'F' for order, and an array-like object for like)

In [22]:
array_true =np.full ((3,3), True, dtype = bool )
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

* Mask

A mask is a special kind of array that tells us which elements of another array to include and<br>
 which ones to exclude. <br>
 The mask has the same shape as the original array, but each element is either True or False.

 A masked array is an array that has some elements marked as invalid or missing. Masked arrays are useful for data manipulation because they allow to perform operations on arrays with missing or invalid data without having to remove the missing or invalid values from the array.<br>

Applications:<br>

* Data cleaning: Masked arrays can be used to clean data by identifying and removing invalid or missing values from an array.
* Data analysis: Masked arrays can be used to perform statistical analysis on data with missing or invalid values.
* Data visualization: Masked arrays can be used to create visualizations of data with missing or invalid values.

In [25]:
'''array_odd = same shape as my_array and, 
element in the new array == True,
 if matching element
 in my_array == odd, 
 otherwise False.'''

array_odd = my_array %2 ==1
print(my_array[array_odd])

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [32]:
new =my_array.copy()
imp_02 = new %2 == 1
# all the elements of "new" are set to the True values in "imp_02" 
# and then assigned the new value -1.
new[imp_02] =-1
print(new)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

np.where (condition,x,y)<br>

Returns an array of indices where a specified condition is true.<br>
 Parameters:

* condition: a boolean array that specifies the condition to check.<br>
* x: An array-like object that specifies the values to return where the condition is true.
* y: An array-like object that specifies the values to return where the condition is false.

Applications:

* Data filtering:  used to filter data by selecting only the elements that meet a certain condition.
* Data transformation: used to transform data by replacing elements that meet a certain condition with a specified value.
* Data analysis: used to perform statistical analysis on data by selecting only the elements that meet a certain condition.


In [39]:
'''np.where, 3 args:
(my_array % 2 == 1) creates an odd Boolean array 

(-1) value to assign to all the odd numbers.

(my_array) is the original array to be modified.'''

n = np.where(my_array % 2 ==1,-1, my_array )
print(n)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

numpy.reshape <br>
Returns a new array with a specified shape. <br>

parameters:

* a: array-like object that specifies the array to be reshaped.
* newshape: An integer or sequence of integers that specifies the new shape of the array.
(order: An optional parameter that specifies the order in which the elements of the array should be read. It defaults to 'C')

Applications:

* Data flattening: numpy.reshape can be used to flatten an array into a one-dimensional array.
* Data transformation: numpy.reshape can be used to transform an array into a new shape that is compatible with another operation.
* Data visualization: numpy.reshape can be used to reshape an array into a format that is compatible with a specific visualization.

In [47]:
# array.reshape((rows,columns)), 
# array.size, total number of elements in the array

print(my_array.size)
my_array.reshape(2,5)


10


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [48]:
'''np.vstack()
  stack arrays vertically
  np.hstack, horizontally'''

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)
```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
* np.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)<br>

Allows you to find the common elements between two arrays and return them as a new array. This can be helpful when you want to compare two datasets and find the overlapping values.Return the sorted, unique values that are in both of the input arrays.

Parameters:
* ar1, ar2array_like
* Input arrays. Will be flattened if not already 1D.
assume_uniquebool
If True, the input arrays are both assumed to be unique, which can speed up the calculation.<br>
If True but ar1 or ar2 are not unique, incorrect results and out-of-bounds indices could result. Default is False.
* return_indicesbool
If True, the indices which correspond to the intersection of the two arrays are returned. The first instance of a value is used if there are multiple. Default is False.
New in version 1.15.0.

Applications:

* Data filtering:to filter data by selecting only the elements that are common to two arrays.
* Data transformation:to transform data by creating a new array with only the elements that are common to two arrays.
* Data analysis: to perform statistical analysis on data by selecting only the elements that are common to two arrays.

In [51]:
'''np.intersect1d(a,b)
finds the common elements between two arrays
and returns them as a new array. '''

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [ ]:
help(np.concatenate)

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [ ]:
my_array = np.arange(10)

mult = my_array*10
print(mult)


print(my_array [0])
print(my_array [-1])
print(my_array [1:8])


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [ ]:
my_matrix = np.array ([[73,55,7],[4,16,7],[83,-4,95]])
print(my_matrix)

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [ ]:
'''args.
starts at 1, 
ends at 50,
 step of 3'''
 
np.arange(1,50,3)

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [ ]:
np.arange(4,1.25,-0.25)

## Ejercicio 16
Lee la imagen "numpy.png"

In [ ]:
from skimage.io import imread
import matplotlib.pyplot as plt

imag=imread("./img/numpy.png")
plt.imshow(imag)
print(imag.shape)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

* Reshaping an array can be useful when you want to perform operations on the data that require a different shape. For example, to reshape an array so that it can be used as input to a machine learning algorithm.



np.reshape <br>

Returns a new array with a specified shape.<br>

np.array<br>

creates a new array.<br>

Parameters:

* object: An array-like object that specifies the array to be created.
* dtype: An optional parameter that specifies the data type of the new array. If not specified, it defaults to the data type of object.
* copy: An optional parameter that specifies whether to copy the data from object. It defaults to True.
* order: An optional parameter that specifies whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory. It defaults to 'K'.

* (subok: An optional parameter that specifies whether to return a subclass of ndarray. It defaults to False).
* (ndmin: An optional parameter that specifies the minimum number of dimensions that the resulting array should have. It defaults to 0.)

Aplications:

* Data creation: to create new arrays from existing data.
* Data transformation: transform existing data into a new format that is compatible with other operations.
* Data analysis:to perform statistical analysis on data by creating arrays with specific shapes and sizes.

In [ ]:
array_4_4= np.array([[0],[0],[0],[0]])
array_4_4.reshape((2,2))

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

* np.random.seed<br>
 set the random seed for random number generator.<br>
* The function takes an integer as an argument and returns None. 
* The seed is used to initialize the pseudorandom number generator, which generates a sequence of numbers that appear to be random but are actually deterministic.
* random seed is used to initialize the generator, which ensures that the same sequence of random numbers is generated every time you run your code.<br>
*  This can be useful when you want to generate random numbers that are reproducible.

Applications:

* Reproducibility: to ensure that a sequence of random numbers is reproducible. By setting the seed to a fixed value, you can generate the same sequence of random numbers every time you run your code.

* Data splitting: to split data into training and test sets. By setting the seed to a fixed value, you can ensure that the same data points are selected for the training and test sets every time you run your code.

* Data shuffling: to shuffle data. By setting the seed to a fixed value, you can ensure that the same shuffling order is used every time you run your code.



In [ ]:
''' random integers between 1 and 10. 
args.
 lowest possible value = 1
 highest possible value -1 = 10
  The size parameter = shape (4, 5, 3) 
  4 rows, 5 columns, and 3 layers.'''
np.random.seed(6)
sqnc= np.random.randint(1,10,size=(4,5,3))
print(sqnc)

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5. <br>
np.full((x,y),Bool)

In [ ]:
f=np.full((10,1),False)
print(f)

## Ejercicio 20
Dado el siguiente array<br>
* x.size, x.shape, x.shape
```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array? x.size
2. ¿Cuántas dimensiones?.x.diim
3. ¿Cuántos elementos tiene cada dimensión?x.shape

In [ ]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x.size, x.ndim, x.shape)