## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [34]:
my_array=np.arange(10)

print (my_array [::])

print (my_array [::-2])



[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [46]:
print(my_array [-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [79]:
print(my_array)
print(my_array [0:3][::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5,reshape(4,5) con una secuencia del 1 al 20, np.arange(1,21)
2. Invierte totalmente la matriz. Tanto las filas, como las columnas [::-1,::-1]

In [82]:
matrix=np.arange(1,21).reshape(4,5)
print(matrix)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [80]:
print(matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```
1. (:) select all rows
2. (:) select all columns
3. (2) up to the second row and column

In [93]:
print(matrix)
print(matrix [:2:,:2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
''' :: 2 ,all rows all columns, :: 2 ,everyother column'''

print(matrix [::2,::2])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [114]:
""":3, 3 first rows, ::-1, inverted """
print(matrix [:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros. (x == loro) / Resuélvelo de dos maneras diferentes<br>
* mask x==loro
* np.where, create a masked array directly from a boolean condition x==loro


Boolean array indexing x[obj.nonzero()]


* This advanced indexing occurs when obj is an array object of Boolean type, such as may be returned from 
comparison operators. A single boolean index array is practically identical to x[obj.nonzero()] where, as 
described above, obj.nonzero() returns a tuple (of length obj.ndim) of integer index arrays showing the True 
elements of obj. However, it is faster when obj.shape == x.shape.

* If obj.ndim == x.ndim, x[obj] returns a 1-dimensional array filled with the elements of x corresponding to the 
True values of obj. The search order will be row-major, C-style. An index error will be raised if the shape of 
obj does not match the corresponding dimensions of x, regardless of whether those values are True or False.

* A common use case for this is filtering for desired element values.

[Numpy Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html)

In [9]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mask = x == "Loro"
print(mask)
x[mask]






[ True False False  True False]


array(['Loro', 'Loro'], dtype='<U5')

In [ ]:
array_filter=np.where(x=="Loro")
print(array_filter)
x[array_filter]

## Ejercicio 9
Crea una secuencianp.(np.arange) de (20) elementos y transformala (reshape) en un array compuesto por 2 matrices de 5x2(2,5,2)

In [ ]:
seq = np.arange(20).reshape(2,5,2)
print (seq)

## Ejercicio 10, 
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

## Ejercicio 11
Crea un array de 10 0s. np.zeros()
¿Cuánto ocupa en memoria? <br>
Sustituye el 4  elemento por 1, e imprime el array por pantalla

array.itemsize returns the size of each element (in bytes). 

array.nbytes returns the total number of bytes used by the array array. This is equal to the product of the number of elements in the array and the size of each element in bytes.


In [148]:
array = np.zeros(10)
print(array,array.size, array.nbytes)
# boolean indexing
array[3]=1
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 10 80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
vector=(np.arange(10,50))
print(vector [::-1])

## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

np.nonzero<br> 
* returns the indices of the elements that are non-zero in an array. It returns a tuple of arrays, one for each dimension of the input array, containing the indices of the non-zero elements in that dimension. <br> 
* The values in the input array are always tested and returned in row-major, C-style order 

In [ ]:
vector=[1,2,0,0,4,0]
mask= np.nonzero(vector)
print(mask)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
martrix_10 =np.random.randint(1,100, size=(10,10))
print(martrix_10, martrix_10.max() ,martrix_10.min())



## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vector_rnd = np.random.random(30)

print(vector_rnd)
print(vector_rnd.mean())

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0

In [2]:
array_2d = np.ones((10,10))
# all elements to 1
array_2d[1:-1:, 1:-1:]
# all to 0 except borders
array_2d[1:-1:, 1:-1:] =0

print(array_2d)

NameError: name 'np' is not defined

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [225]:
matrix_08 = np.zeros((8,8), dtype=int)

# everyother row and column odd = 1
matrix_08[1::2, ::2] =1
# everyother row and column even =1
matrix_08[::2, 1::2]= 1 
print(matrix_08)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

numpy.tile(A, reps) 
Creates an array by repeating the input array.<br>
* arguments: 
* the input array to be repeated 
* a tuple specifying the number of times to repeat the array along each dimension. 


In [ ]:
matrix_tile = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(matrix_tile)

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
matrix_aleat = np.random.randint (1,20,(5,5))
matrix_aleat = (matrix_aleat - np.mean(matrix_aleat) / np.std(matrix_aleat))
print(matrix_aleat)

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8. (>3 and <=8) =-1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
#1
seq=np.arange(11)
#2
# seq[(seq>3)&(seq <=8)] =-1
# print(seq)
# 3
seq[(seq>3)&(seq <=8)] *= -1
print(seq)